### ISSUE TITLE
第一次启动的时候 翻译组件报错了

### ISSUE THREAD

**Issue by four-li** [kakuilan/hyperf-apihelper#22]
[CRITICAL] Call to undefined method Hyperf\Translation\TranslatorFactory::trans()[346] in /data/vendor/kakuilan/hyperf-apihelper/src/Validation/Validator.php
[CRITICAL] #0 [internal function]: Hyperf\Apihelper\Validation\Validator->rule_enum()
#1 /data/vendor/kakuilan/hyperf-apihelper/src/Validation/Validator.php(172): call_user_func_array()
#2 /data/runtime/container/proxy/App_Middleware_ApiValidationMiddleware.proxy.php(217): Hyperf\Apihelper\Validation\Validator->validate()

**Comment by kakuilan** [comment]
休假中，过两天再看看

**Comment by kakuilan** [comment]
swoole、hyperf版本分别是多少？

**Comment by kakuilan** [comment]
我这边没问题
swoole 4.5.9
hyperf 2.1.1
hyperf/translation 2.1.0

**Comment by four-li** [comment]
translation: 2.1.0
hyperf: 2.1.0
swoole: 4.6.7

起初我担心是受项目里其它问题影响，于是我重新重新创建项目（以上环境）安装apihelper，还是会有这个问题
Validator里只要用到了如enum自定义规则调用了trans就报错，。

**Comment by kakuilan** [comment]
打包你的源码传上来我看看？
